{{- if and .Values.service.enabled }}
{{- $chart_name := (include "ark-cluster.fullname" .) }}
{{- $labels := (include "ark-cluster.labels" .) }}
{{- $gameudp := $.Values.containerPorts.gameudp }}
{{- $queryudp := $.Values.containerPorts.queryudp }}
{{- $rcon := $.Values.containerPorts.rcon -}}
{{- range $name, $server := .Values.servers }}
{{- if .ports }}
  {{- $gameudp = default $gameudp .ports.gameudp }}
  {{- $queryudp = default $queryudp .ports.queryudp }}
  {{- $rcon = default $rcon .ports.rcon }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $chart_name }}-{{ $name }}-tcp
  namespace: {{ $.Release.Namespace }}
  labels: {{- $labels | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
    {{- if $.Values.commonLabels }}
      {{- include "ark-cluster.tplValue" (dict "value" $.Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if or $.Values.commonAnnotations $.Values.service.metallb_shared_ip }}
  annotations:
    {{- if $.Values.service.metallb_shared_ip }}
      metallb.universe.tf/allow-shared-ip: {{ $chart_name }}-{{ $name }}
    {{- end }}
    {{- if $.Values.commonAnnotations }}
      {{- include "ark-cluster.annotations" (dict "annotations" $.Values.commonAnnotations "context" $) | nindent 4 }}
    {{- end}}
  {{- end }}
spec:
  type: {{ $.Values.service.type }}
  {{- if $.Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ $.Values.service.externalTrafficPolicy }}
  {{- end }}
  ports:
  - port: {{ $rcon }}
    name: rcon
    targetPort: {{ $rcon }}
  selector:
    app.kubernetes.io/component: {{ $name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $chart_name }}-{{ $name }}-udp
  namespace: {{ $.Release.Namespace }}
  labels: {{- $labels | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
    {{- if $.Values.commonLabels }}
      {{- include "ark-cluster.tplValue" (dict "value" $.Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if or $.Values.commonAnnotations $.Values.service.metallb_shared_ip }}
  annotations:
    {{- if $.Values.service.metallb_shared_ip }}
      metallb.universe.tf/allow-shared-ip: {{ $chart_name }}-{{ $name }}
    {{- end }}
    {{- if $.Values.commonAnnotations }}
      {{- include "ark-cluster.annotations" (dict "annotations" $.Values.commonAnnotations "context" $) | nindent 4 }}
    {{- end}}
  {{- end }}
spec:
  type: {{ $.Values.service.type }}
  {{- if $.Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ $.Values.service.externalTrafficPolicy }}
  {{- end }}
  ports:
  - port: {{ $gameudp }}
    name: game
    targetPort: {{ $gameudp }}
    protocol: UDP
  - port: {{ $queryudp }}
    name: query
    targetPort: {{ $queryudp }}
    protocol: UDP
  selector:
    app.kubernetes.io/component: {{ $name }}

{{- end }}
{{- end }}

